name: Publish binary

on: 
  push:
    branches:
      - main
    tags:
      - '*'
  workflow_dispatch:

jobs:
  publish:
    name: Publish for ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            asset_name: mapvas-linux.zip
          - os: macos-latest
            asset_name: mapvas-macos.zip
    steps:
      - uses: actions/checkout@v3
      - name: Build
        run: |
          cargo build --release --locked
          zip -j mapvas.zip target/release/mapvas target/release/mapcat
      - name: Upload binary
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: mapvas.zip
          asset_name: ${{ matrix.asset_name }}
          tag: ${{ github.ref }}
