name: Publish

on: 
  push:
    branches:
      - main
    tags:
      - '*'
  workflow_dispatch:

jobs:
  publish:
    name: Publish for ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            asset_name: mapvas-linux.zip
          - os: macos-latest
            asset_name: mapvas-macos.zip
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      - uses: katyo/publish-crates@v2
        with:
          registry-token: ${{ secrets.CARGO_REGISTRY_TOKEN }}
          ignore-unpublished-changes: true
      - name: Build
        run: |
          cargo build --release --locked
          zip mapvas.zip target/release/mapvas target/release/mapcat
      - name: zip
        uses: thedoctor0/zip-release@0.7.5
        with:
          type: 'zip'
          filename: 'mapvas.zip'
          directory: target/release
      - name: Upload binary
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: mapvas.zip
          asset_name: ${{ matrix.asset_name }}
          tag: ${{ github.ref }}
